### ISSUE TITLE
Dark grey “Described Value Domain” artefact on the diagram is misleading.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#10]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-3|UM|28|861
***
### Issue Description
Dark grey “Described Value Domain” artefact on the diagram is misleading. It is hard to understand its purpose with reference to its description.
### Proposed Solution
Remove the artefact from the diagram. Optionally describe it in more consistent way.

**Comment by VincDV** [comment]
In the 21/04/2017 teleconference it was agreed that the comment is right because in the diagram there are two different entities named "Described Value Domain", of which the grey one is wrong and should be properly amended.
It was also agreed to give a better explanation of the "described Value Domain" by stating explicitly that it is equivalent to "non-enumerated Value Domain".

**Comment by amattioc** [comment]
Fixed in manual 2.0
