### ISSUE TITLE
The ":" is not specified before

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#110]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-8|RM|22|399
***

### Issue Description
The ":" is not specified before

### Proposed Solution
Clarify the notation ":"

**Comment by capacma** [comment]
The notation "parameter : type" specifies the type of the parameter.

Replace ::== with ::= at line 381.

Explain "clauses" at line 370.

The sentence at line 371 is wrong because it mixes syntax and types. 
**Replace:**
The syntax of the operators is defined by meta-expressions, which denotes the signature of an operator, that is, its name, the list of the input parameters, the possible special keywords and the respective types
**with:**
The syntax of an operator is defined by meta-expressions which denote the name of the operator, the parameters and the accompanying syntactical elements.

**Comment by vignola** [comment]
@capacma  my comment was due to the fact that the notation ":" is used and never explained before.
It should be included in the "Syntactical convention" before to be used

**Comment by linardian** [comment]
Refers to old version of documentation
