### ISSUE TITLE
DimensionType is a parameter more linked to SDMX while VTL use Identifiers.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#111]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-9|RM|24|438
***

### Issue Description
DimensionType is a parameter more linked to SDMX while VTL use Identifiers.

### Proposed Solution
Change the parameter name in identifierType

**Comment by capacma** [comment]
The term identifier is not correct. We should use "identifier component".
To enhance the presentation of the language we should use the term "dimension" instead of "identifier component". See issue #269.

**Comment by VincDV** [comment]
As a basic VTL assumption, the VTL terminology  (including the term "identifier") is deriver from GSIM, in order to make VTL applicable to the IMs mapped to GSIM, like SDMX and DDI.
The GSIM choice of the term "identifier" seems to me much more appropriate than "dimension", because the latter gives the wrong impression that the standard is applicable only to dimensional data (like SDMX originally), while the former clearly refers to any data, both dimensional and unit data (like GSIM and VTL).
Therefore I agree with the proposed solution of changing the parameter name coherently with the term "identifier" currently used in the IM.

**Comment by linardian** [comment]
Refers to old version of documentation
