### ISSUE TITLE
Definition of a new DataStructure.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#130]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-27|RM|30|789
***

### Issue Description
In case of definition of a new DataStructure (not reusable).

### Proposed Solution
It is not very clear: this is the case in which a new dataset is defined without referring to any existing data structure? If yes, give a more clear sentence.

**Comment by bellomarini** [comment]
Yes, as far as the DataStructures are concerned, the current DDL operators allow two modes:

1. reusable definitions of DataStructures;
2. non-reusable definitions of DataStructures. 

While option 1 is clear, since a specific name is assigned to the DataStructure, the second one is quite vague, since a DataStructure should have a name anyway. The proposed solution is to improve the explanation, saying that in such cases an internal name for the DataStructure is automatically generated, though it is not visible to the user.

**Comment by linardian** [comment]
Refers to old version of documentation
