### ISSUE TITLE
Forbid ambiguous variable assignments like D:=1,2*D

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#16]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-7|UM|47|1609
***
Variable scope feature might be misleading for non-technical user.
Given example 
```
D := 0.2 * D1 + 0.8 * D2
D := 1.2 * D
```
Intuitively should be considered as error.

## Proposed solution ##

Forbid assigning to the same variable name twice in the same scope.

## Discussed Solution (for voting)

**Comment by dragan-ivanovic** [comment]
The statement that the example is an error is not well founded.  Thee example:

```
D := 0.2*D1 + 0.8*D1
D := 1.2*D
```

is clear. The second assignment to `D` hides the effects of the first assignment to `D` from the Coddenham that follows.

**Comment by dragan-ivanovic** [comment]
The part of the comment that refers to difficulties a non-technical user may have reading this example can be addressed by isolating these technical details into a frame marked e.g. with a special icon and label ("Technical detail"), so that it is clear this part of the text is aimed at the technical users.

**Comment by bellomarini** [comment]
My first concern about the approach described in the user manual is that it relies on the order in which the statements appear in that the program. I understand that the *hiding* mechanism rules out ambiguous assignments, but it works only if the execution order is established, which is not the case in a declarative language, as we said VTL is.

Actually, if we swap the two lines of the example, we obtain

```
D := 1.2*D
D := 0.2*D1 + 0.8*D2
```

which cannot be even calculated, as we do not know the value for D in the first statement.
In general, even in cases when the program could be executed, we could get different results depending on the order, which is not desirable.
The first proposal is then forbidding multiple assignments for the same variable parameter.

My second concern about the approach is the tolerance of some form of recursion within a statement, as we have in:

```
D := 1.2*D
```

As in general we forbid cyclic assignments, since they would hinder the determination of a correct ordering in the statements (in facts preventing the declarative approach), we should forbid self-loops as well. Moreover, if we forbid multiple assignments (first proposal), a self-loop statement could never be calculated, since no other statement could have given values to its operands. In the example, no other statements could have assigned D before the one at hand. My second proposal is therefore forbidding self-loops.

**Comment by dragan-ivanovic** [comment]
After looking at arguments by @bellomarini I think it makes sense to forbid assigning twice to the same variable name in the same scope. Although strictly speaking this restriction is not necessary, I agree that it can be somewhat confusing or simply a result of an error. So, in this way we keep on the safe side.

**Comment by amattioc** [comment]
clarified in rows 1650-1661 2.0 manual
