### ISSUE TITLE
Replacement of semicolons

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#174]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB-30|RM|53|1874-1876
***

### Issue Description
The semicolons should be replaced by commas at the end of each clause.

### Proposed Solution
See comment below

**Comment by capacma** [comment]
if we use the comma as the separator of the clauses then we need to change the syntax of some clauses, like "keep", that use the comma as separator of a list of names (e.g. keep a, b, c).
If we use the semicolon as the separator of the clause we can maintain that syntax and write:
keep a, b, c ; keep d ; ...
otherwise we have to change the syntax of the clauses and add parenthesis:
keep ( a, b, c ) , keep ( d ) , ...

**Comment by linardian** [comment]
Referes to an old version of documentation
