### ISSUE TITLE
Syntax & examples - "func_dep".

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#213]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-10|RM|103|func_dep p. 103
DI-11|RM|103|func_dep p. 103
***

### Issue Description
(DI-10) The syntax of func_dep is the syntax for creating lists and tuples. As an example of possible confusion, func_dep(ds, (x),  (y)) is the same as func_dep(ds, x, y), because enclosing single expressions in parentheses does not change the type or value of the enclosed expression. So, (x) and (y) are the same as x and y, respectively.  
(DI-11) The meaning of identifiers in the examples for func_dep is different from the standard meaning of identifiers in VTL 1.1 expressions. The standard is passing by value, but then in func_dep(ds, x, y) the second and third arguments would be the values held in variables x and y, not the component names "x" and "y" as such. 

### Proposed Solution
(DI-10) Fix the use of lists and tuples. list() is the empty list, list(A) is a singleton list whose only element is the result of sub-expression A.list(A,B,C) is a three-member list whose elements are the results of evaluating sub-expressions A, B and C, respectively. (A, B, C) is an ordered triple (not a list) whose elements are the results of evaluating sub-expressions A, B and C, respectively.(A) is the same as A.
(DI-11) The second and the third argument to func_dep must be lists of strings (i.e., component names have to be provided as quoted strings). The correct example is: func_dep(ds, list("FISCAL_CODE"), list("NAME")) or, if we allow single strings: func_dep(ds, "FISCAL_CODE", "NAME").

**Comment by vignola** [comment]
Could the following can be possible alternative solutions?
**1)**
**func_dep** ( ds , _listCompFrom_ , _listCompTo_ )

where
_listCompFrom_,  _listCompTo_ : list<list<Identifiers-ref>>

so that the examples would be
ds_2 := **func_dep** ( ds_1, list(FISCAL_CODE), list(NAME))

ds_3:= **func_dep** ( ds_1, list(FISCAL_CODE ), list(list(NAME), list(DATE_OF_BIRTH),list(PLACE_OF_BIRTH))

**2)**

**func_dep** (_listCompFrom_ , _listCompTo_ )

where
_listCompFrom_, _listCompTo_ : [ds.Identifier | list(ds.Identifier { , ds.Identifier } *)]
so that the examples would be:

ds_2 := **func_dep** ( ds_1.FISCAL_CODE, ds_1.NAME)

ds_3:= **func_dep** (ds_1.FISCAL_CODE , list(ds_1.NAME, ds_1.DATE_OF_BIRTH, ds_1.PLACE_OF_BIRTH))

**Comment by linardian** [comment]
Refers to an old version of documentation
