### ISSUE TITLE
Specify partition by as optional.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#238]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-37|RM|133|Analytic functions
***

### Issue Description
Partition by optional - defaults to all dimensions apart from the order by dimensions when not all dimensions have been specified either in order by or partition by.

### Proposed Solution
Specify partition by as optional.

**Comment by capacma** [comment]
This feature increases code reuse because it eliminates the need to specify the dimensions in the partition by clause. 
Example: suppose we have a dataset ds with the following dimensions: ref_area, bop_item and time. Then the expression:
 analytic_function ( ds ) over ( order by time )
is treated by VTL as if it were:
 analytic_function ( ds ) over ( partition by ref_area, bop_item order by time )

**Comment by linardian** [comment]
Refers to old version of documentation
