### ISSUE TITLE
Datasets & identifiers.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#253]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-14|RM| |761
***

### Issue Description
Not all datasets have a unique identifier.

### Proposed Solution
Add support for datasets with implicit identifiers (like row number, universal numerical fingerprint generated keys, uuid, etc.)

**Comment by bellomarini** [comment]
Probably there should be support for implicit identifiers in the sense that in absence of identifying values, there should be mechanisms to generate them automatically. However, this comment specifically refers to the structure of Datasets, since in the RM we say that there must be at least an Identifier component. 

I suggest that we keep the assumption that in the definition there is at least one identifier component. A Dataset without Identifiers, as we said in the meeting in Rome, can exist, but is indeed a Constant. Therefore there is no need to use define Dataset.
