### ISSUE TITLE
Power operator.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#276]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-67|RM|new |
***

### Issue Description
There is a very important use case that involve the power operator. Sometimes the obs value must be multiplied by a power of 10 having as exponent a value assumed by the codelist UNIT_MULTIPLIER. In the SWG context it is mentioned to express this transformation using VTL but actually there is no possibility to do this using the power operator.

### Proposed Solution
Extend the power operator to power(base,ds.component) where component is a numeric codelist.

**Comment by capacma** [comment]
OK this change is to make the power function to have 2 dataset operands (instead of 1).
For uniformity of treatment, the same change should be applied to all functions that currently have more than 1 operand but only 1 operand can be a dataset (example: mod, log, round, trunc, substring, replace  etc.).
