### ISSUE TITLE
Procedures in Part 2.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#287]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-3|UM|53|
***

### Issue Description
There are no procedures in Part 2.

### Proposed Solution
Remove (or add in detail).

**Comment by capacma** [comment]
Proposal 1.
I then propose to eliminate the type "dataset" without any further specification of the dataset components (as in "ds as dataset") because:
•	the keyword dataset (without any further specification) does not provide any semantic information
•	it is not coherent with the VTL assumptions (strongly typed language, semantic checks done at compile time)
•	the compiler cannot say whether a VTL fragment of code is correct or not (at compile time)
•	the compiler and the type system would become too complex

In addition I propose to forbid any other situation in which the compiler does not know whether a VTL fragment of code is correct or not. For example, the type of a function argument should be mandatory (now it is optional).

**Comment by capacma** [comment]
Proposal 2.
I propose that the argument type is mandatory in **define function** and **define procedure**.

The rationale is allowing VTL to compute all necessary type information at compile time.

**Comment by linardian** [comment]
Refers to old version of documentation
