### ISSUE TITLE
See Example, give a more illustrative example.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#306]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-22|RM|95|
***

### Issue Description
The first example (" 1) ds_check := population exists_in_all urbanization_rate ") is not correct: in this case, the resulting "CONDITION" component in the ds_check should contain only "true" values in all rows.

### Proposed Solution
Perhaps give a more illustrative example.

**Comment by vignola** [comment]
The example is really wrong. Instead of correct with value "true" for every rows, according with the proposed solution, I propose to change the example with the following one:


population
TIME	|GEO	|AGE	|SEX	|POPULATION
:--|:--|--:|--:|--:
2012	|Belgium	|Total	|Total	|11094850
2012	|Greece	|Total	|Total	|11123034
2012	|Spain	|Total	|Total	|46818219
2012	|Malta	|Total	|Total	|417546
2012	|Finland	|Total	|Total	|5401267
2012	|Switzerland	|Total	|Total	|7954662

urbanization_rate
TIME	|GEO	|AGE	|SEX	|RATE
:--|:--|--:|--:|--:
2012	|Belgium	|Total	|Total	|0.023
2012	|Greece	|Total	|M	|0.286
2012	|Spain	|Total	|Total	|0.064
2012	|Malta	|Total	|M	|0.043
2012	|Italy	|Total	|Total	|NULL
2012	|Switzerland	|Total	|Total	|0.08

ds_check
TIME|	GEO	|AGE	|SEX	|CONDITION
:--|:--|--:|--:|--:
2012	|Belgium	|Total	|Total	|true
2012	|Greece	|Total	|Total	|false
2012	|Spain	|Total	|Total	|true
2012	|Malta	|Total	|Total	|false
2012	|Finland	|Total	|Total	|false
2012	|Switzerland	|Total	|Total	|true

**Comment by linardian** [comment]
Refers to old version of documentation
