### ISSUE TITLE
Description is unclear/incorrect.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#308]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-24|RM|102|3518
***

### Issue Description
The description is unclear, and perhaps not even really correct. 

### Proposed Solution
Perhaps it should be (if I understand correctly): "The unique operator verifies that there is one and only one Data Point that satisfies the input conditions."

**Comment by vignola** [comment]
The semantic in the RM of the uniqe operator is: 
_The unique operator verifies the presence of one single Data Point having true as the value for the Measure component._
and the syntax is: **unique** (ds)
This means that the operator is applied to a dataset having  boolean measures (after the meeting in Rome, having only one boolean measure)

I like the proposed solution except for the terms "input conditions"  because in the syntax  there is no condition. So I would propose:
_"The unique operator verifies that in the input dataset, there is one and only one Data Point having the boolean measure equal to "true"_

**Comment by dragan-ivanovic** [comment]
If I understand well, `unique(ds)` should be then the same as `count(ds[filter condition])=1`?

**Comment by linardian** [comment]
Refers to old version of documentation
