### ISSUE TITLE
Explanation for "compulsory"

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#325]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-41|RM|162|5236
***

### Issue Description
I do not suppose that "else" is compulsory - and in that case "else ds_3" should be in curly brackets.

### Proposed Solution
Revise or explain why it is actually compulsory.

**Comment by vignola** [comment]
I propose to make optional **else** assuming that in case the "else" it is not specified, only the data points evaluated to "true" will be considered in the returning dataset.

In this case the syntax will be:
If ds_cond_1 then ds_1 { elseif ds_cond_2 then ds_2}* {else ds_3}

I also propose to change the return text in the following way (_my english is not so good so please correct it_)
Returns
If the input parameters are Boolean scalars then the operator returns the constant of the first evaluated 
true condition. If no condition evaluates true then c_3 is returned. Only the _true_ condition will be evaluated if the **else** is omitted.
If  the  input  parameters  are Datasets  then  the  operator  returns  a  Dataset  having  all  the  Identifiers  and  the Measure Component~~s~~ of  the  input  ones. The data Points of the returned dataset are those of the ds_1, ds_2 (and ds_3) input datasets matching with Data Points of related conditions ds_cond_1, ds_cond_2 (else) when they are evaluated to “true” (“false”). If the else is not specified only the true Data Points of input condition are considered.~~ ,  composed  by  Data  Points  retrieved  in  the  input  Datasets  when  the  relative condition on the relative Boolean Measure Component evaluate true (false in else case).~~

I will remove the semantic specification because do not add something more. To me it is better to specify clearly what is the returning dataset

**Comment by linardian** [comment]
Refers to a previous version of the documentation
