### ISSUE TITLE
example 2 - Explain the example clearly; perhaps add different example; add more examples.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#327]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-43|RM|163|
***

### Issue Description
It is difficult to understand example 2, and I am not even sure whether it is correct. I think that the content of the "population" input table is quite unhelpful, since, for each combination of Identifiers, it always has cases that satisfy and cases that do not satisfy the condition (both M and F, while the condition is population.SEX = "F").

### Proposed Solution
Explain the example clearly; perhaps add different example; add more examples.

**Comment by vignola** [comment]
I also propose to change the example and provide one that is more significant, at the same time I would avoid to use the component name "CONDITION" in the example if there is no an intermediary step in which this component is showed because it generates only confusion (it is no clear how CONDITION can match with "rate" component if, in the datasets unemp_rates_1 and unemp_rates_2, the component measures have different names).

**Comment by vignola** [comment]
This issue can be solved only after to have decided how to treat the membership with Identifiers, when we resolve it than the measure "POPULATION" can also be eliminated.

**Comment by linardian** [comment]
Refers to old version of documentation
