### ISSUE TITLE
Easy function for removing and for adding datapoints from/to a dataset.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#335]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-51|UM|-|
ESTAT-51|RM|-|
***

### Issue Description
There should be an easy function for removing and for adding datapoints from/to a dataset.
See also #275 

### Proposed Solution
E.g. remove(ID = "employee2", AGE = 34, OFFICE = "A23") from (ds_2) should remove the datapoint (or datapoints) that have these Identifier codes, while add(ID = "employee2", AGE = 34, OFFICE = "A23") from (ds_2) should add this datapoint with the specified codes, with null values under unspecified Measure and Attribute components, and if an Identifier in the dataset is not specified, this datapoint should be added with each already existing code under that Identifier.  It should be just as well possible to specify Measures and Attributes in these functions.

**Comment by egreising** [comment]
I see it as a very powerful function for data management. I would suggest using add (-----) **TO** (dsx) instead of "from" (for the add function)

**Comment by VincDV** [comment]
The proposed solution is not feasible according to the basic properties that are the fouldation of the VTL.
A better explanation is given in my comment about #275, which is valid even for this Item.

As said also in #275, I propose to close the issues #275 and the #335 (this one) because they are not feasible, and continue the discussion on the Issue #272, which is the only possible alternative.

**Comment by capacma** [comment]
I agree with the comment by @VincDV to close the issues #275 and the #335 and to continue the discussion on #272.
