### ISSUE TITLE
Consistency in naming conventions.

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#336]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAT-52|UM|-|
ESTAT-52|RM|-|
***

### Issue Description
Naming conventions (camel case, underscoring, simple spaces, etc.) often vary inconsistently, i.e. regardless of functionality (functions, keywords, etc.). Obviously, consistency would be better.

### Proposed Solution
E.g. camel case for built-in operators, and underscoring recommended for user-defined functions and variable, etc. I would normally avoid white spaces in any names.
@capacma 
Names are case sensitive (RM 368 at page 22).
Spaces are not allowed.
Object names can be enclosed in single quotes '

**Comment by dragan-ivanovic** [comment]
All keywords and unquoted identifiers are internally converted to lowercase.  Therefore, using CamelCase or a similar scheme is irrelevant.

Regarding spaces in identifiers, these cannot exist by definition. Therefore, `define function` is not a single identifier, but two keyword tokens one after another. The same goes for `define dataset`.  The choice of `defineDataset` is bad because it is the same as `definedataset` or `dEFINEdATASET`.

**Comment by capacma** [comment]
Names in VTL 1.1 are case sensitive, see page RM 368 at 22.
Spaces are not allowed.
Object names can be enclosed in single quotes ' and ' (e.g. 'myschema.myobject' ) this is necessary when the name contains "." (membership operator).
