### ISSUE TITLE
homogenization of VTL 1.1 syntax

### ISSUE THREAD

**Issue by capacma** [sdmx-twg/vtl#356]
### Issue Description
The syntactical style of the VTL operators must be harmonised
### Proposed Solution
Document provided by Luigi

[operators_syntax_guideline.pdf](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/995273/operators_syntax_guideline.pdf)

**Comment by capacma** [comment]
About chapter 6. Varargs (functions with variable number of arguments)
The proposed solution uses a new type of object "list of datasets". Currently this is not a VTL object therefore we need to defined it in the information model.
Please consider that other solutions exist, for example we can change the syntax of the operators from functional to infix. Instead of:
  union ( ds1, ds2, ..., dsN)
the syntax would be:
  ds1 union ds2 ... union dsN
The same solution could be applied to the intersect operator (by the way, this operator can be simply binary).

**Comment by capacma** [comment]
What is the type of a list of components (example: keep [ comp1, comp2 ] )?

**Comment by capacma** [comment]
Examples of new syntax style for analytic functions, aggregate functions, time-series functions, clauses:
[Examples of new syntax style.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1007417/Examples.of.new.syntax.style.docx)

**Comment by vignola** [comment]
Hi all,
I  put, me too, some operators with the new syntax. Most of the operators remain the same.
I hope to have well interpreted the guidelines by Luigi.
[Examples.of.new.syntax.style_LV.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1008433/Examples.of.new.syntax.style_LV.docx)

**Comment by bellomarini** [comment]
And my experiments.

[operators_experiments_LB.pdf](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1008466/operators_experiments_LB.pdf)

**Comment by bellomarini** [comment]
@capacma I have a general question about your examples.
Sometimes you use syntactic objects that are not specified and I assume they are just placeholders for the corresponding literals.

For example:

lag ( ds, offset := 1, default := 0, order_by := [ time_period ] )

actually, do you mean something like:

lag ( ds, offset := 1, default := 0, order_by := [ '2012-12-31 2013-12-31' ] )

whatever the literals for the time period are.

Is this right?

**Comment by bellomarini** [comment]
Here, I'd say that the two values for the directions are strings:

```
sum ( ds, order_by := [ time_period ] ,  direction1 := "current_row" , direction2 := "unbounded_preceding" ] )
```

**Comment by bellomarini** [comment]
@capacma shall we use the strings as follows?

```
sum ( ds, group_by := [ ref_area, partner ] )
```

which becomes:


```
sum ( ds, group_by := [ "ref_area", "partner" ] )
```

and

```
sum ( ds, along := [ time_period ] )
```

which becomes:

```
sum ( ds, along := [ "time_period" ] )
```

**Comment by bellomarini** [comment]
@vignola I have the same question/comment as for @capacma 's experiments:

```
ds_3:= func_dep ( ds_1, [FISCAL_CODE], [NAME, DATE_OF_BIRTH,PLACE_OF_BIRTH])
```

should it become as follows?
```
ds_3:= func_dep ( ds_1, ["FISCAL_CODE"], ["NAME", "DATE_OF_BIRTH","PLACE_OF_BIRTH"])
```

The rationale of all these comments could be the following. I'd rather try to keep in the language as few data types as possible. This means that I'd try to use strings to denote components, datasets (BTW: we already use strings to embed datasets identifiers in the GET). In this way we don't have any possible clashes with the names of variable parameters, which would be the only syntactic objects without any explicit type constructor. Does it make sense?

**Comment by capacma** [comment]
@bellomarini and @vignola 
we can define the components as strings but then the components are known only at run-time, the structure of a dataset is unknown at compile time therefore VTL changes radically. 
This is a huge change and needs further reflections.

**Comment by capacma** [comment]
@bellomarini 
The clash between the different types of names (function parameters, components, "calc" new variables, etc.) is not an issue provided that we clearly define the priority, e.g., when VTL analyses a name first VTL looks in the components (for example when the compiler analyses a clause), then in the function parameters, then in the namespace of the datasets. In this way here is no ambiguity and we leave the user to define its own naming conventions.

**Comment by capacma** [comment]
a good reason to write the component names without "" (so they are not strings) is that it allows the user or a program to discover which are the components used in a program so I would be in favour of not defining them as strings. 
Of course this implies to have a distinct syntactical category.

**Comment by vignola** [comment]
Luigi,
do you want to use it for every id (dataset id, component id, value domain id....) ? 
Because in this case the example should be:
ds_3:= func_dep ( "ds_1", ["FISCAL_CODE"], ["NAME", "DATE_OF_BIRTH","PLACE_OF_BIRTH"])
or 
"ds" [ keep [ "comp1", "comp2", "comp3" ] ]
unfold ( dimension := "ref_area", measure := "os_value", elements := ["EU25", "BG", "RO"] )
is it correct?

**Comment by bellomarini** [comment]
@vignola , @capacma I don't have strong opinions... I think it's just a point to reflect on. Maybe we can leave it as it is, but I agree that we should define a specific syntactic category and verify that we have the appropriate language type. We also have to understand whether there is any form of clash between dataset names (in the implicit GET) and component names.

@vignola ds_1 in your example, maybe ```ds_1``` should go without quotes, as it is looks like a variable parameter and we can assume it has been defined somewhere else. Otherwise, if you assume it to be a dataset and want to use the implicit GET, you should leave it as it is.

**Comment by vignola** [comment]
Yes in the example I supposed to use an implicit GET. In this case I shoul use the "" following your new porposal?

**Comment by vignola** [comment]
I want to make this reflection, because I see the point of Luigi.
If I understand well if we have an identifier that uses characters not allowed, actually we need to use "". For example if the dataset id is STSIND_PROD+ESTAT+1.0 we need to refer to it (using the implicit get) as "STSIND_PROD+ESTAT+1.0" becasue of the "+" and "." characters are not allowed. So the software should be anyway able to recognize if a parameter is really a string or an id (of component, dataset etc..) also if we do not introduce the last change proposed by Luigi.
If it is correct what I am saing (I am not so sure ;) ), we need to decide if we want it as a fixed rule or only as exceptional rule and in this case I would be in favour for a fixed rule.
What we should absolutelly check is that there is no ambiguity in writing rules for every operator so that, by the syntax, the software is able to understand if a term having "", is a string or an id.

**Comment by bellomarini** [comment]
@capacma @vignola 

How things are now:
--------------------

* **implicit GET**: name of the dataset without quotes
* **explicit GET**: name of the dataset with the quotes
* **components in clauses**: name of the component without quotes
* **name of a value domain subset**: name of the value domain subset without quotes
* **other artefacts**: name of the artefact without quotes

Observations
-------------

* do we have a data type in the language for each of them?
* if so, we allow for artefact-type expressions... not well defined
* how to sort out ambiguities?
* what if we want to add operators working on other artefacts?
* shall we simply resort to the IDENTIFIER data type and say that every thing is an IDENTIFIER?

I don't have a clear answer/proposal yet. I need to think it over :-)

**Comment by vignola** [comment]
I had understood that if the name of the dataset contained not valid characters (like "+" or "."), the name had to be included with quotes.

**Comment by capacma** [comment]
The character used for quoting identifiers (object names) is the single quote, e.g. 'mydataset+1'  
The character used for denoting a string is the double quote, e.g. "mystring"
Please confirm or disagree.

**Comment by vignola** [comment]
This I understood at the beginning but yesterday with the Luigi proposal I was a little bit confused because the component name is an identifier so how many representation can we have?

**Comment by fewagener** [comment]
So far I have only found one numeric operator that need to be changed:
listsum (ds { , ds } * )
should be
listsum ([ds1, …, dsn] )
or we could also represent this as listsum ([{ds1}+]) though it's probably more complicated to understand for users
If I'm not mistaken, the rest of numeric operators remain as they are currently, e.g.:
round(ds, decimals)
abs(ds)
log(ds, base)
...

**Comment by egreising** [comment]
For String operators, 4 of them remain unchanged and another 4 include parameters now explicit instead of positional.
[Examples.of.new.syntax.style-StringOperators.docx](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/1023929/Examples.of.new.syntax.style-StringOperators.docx)

**Comment by linardian** [comment]
Notes on obsolete version of documentation
