### ISSUE TITLE
The Set List description

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#47]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-1|UM|31|
***

### Issue Description
The statement "The Set List refers only to the Values contained in the list (e.g. the country codes), without the associated categories (e.g. the names of the countries)" is not aligned with the syntax of Value domain subset (if they are the same object) because it contains the description.

### Proposed Solution
Eliminate the description from the syntax or add it the text of the user manual.

**Comment by bellomarini** [comment]
Correct: "description" should not be in ValueDomainSubset.

**Comment by VincDV** [comment]
In the 21/04/2017 teleconference it was agreed that the comment is correct and should be accepted, as also Luigi proposed, and therefore that the description should be eliminated from the syntax for defining the Value Domain Subset, because it is alreadi given for the Code Item.
It was underlined that SDMX and GSIM have two fields to give descriptions for Code Items, called Label and Description (the former is short and the latter may be a long description) and it was discussed the opportunity of allowing the same in the VTL IM. It was considered that if the description is changed for the Code Item it should be changed also for all the other artefacts and that the VTL don't use the descriptions at all, so that it would be better to eliminate the desrtiprions rather than making this part more complex, even because it wouldn't be possible to comply with all the possible ways of giving descriptions, so that it would be better to consider the description as part of the implementation.
It was agreed to leave the descriptions as they are (unique field), to find a different name for the "description" field in order to avoid ambiguities in respect to SDMX and to explain that this form of description is not essential for the VTL and is not mandatory in the implementations, so that different approaches can be adopted.
