### ISSUE TITLE
General behaviour of operations on datasets: Reference Manual not aligned with User Manual

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#6]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-6|UM/RM|87|
BDI-12|UM/RM|88|All
BDI-24|UM/RM|88|All
BDI-14|UM/RM|90|All
BDI-21|UM/RM|90|All
LV-7|UM/RM|90|3162
***
The general behaviour of operations on datasets is not aligned with the reference manual (see table page 13)
The behaviour on the Data Sets' Identifiers of the binary operators (like +, -, *, /, power, nroot … and so on) specified in the reference manual is wrong and not consistent with the "general behaviour of the operators on Data Sets"  specified in the user manual.  In particular, the user manual says that binary operations would be allowed either if the operand Data Sets have the same components (strict constraint) or if the identifiers of one them is a superset of the identifiers of the other one (relaxed constraint). Instead the reference manual specifies that  the operands "must have at least one Identifier Component in common"  and that the result Data Set will have "the  superset of the Identifier Components" of  the operands. The expressions  specified according to the constraints and the behaviour of  the reference manual would give results inconsistent with the VTL IM, having an inconsistent and misleading semantics and would not allow to check for formula definition errors.  For example consider what would happen in the following case by applying the behaviour specified in the reference manual: DS1: deposits by branch and currency, DS2: deposits by branch and NACE, DS3 = DS1 + DS2 -> deposits by branch, currency and NACE  ???    NO!! (example is missing: see the original Word file) The result would not match with its own definition, in fact it is not equal to deposits by branch, currency and NACE and the figures would be dramatically wrong, including the total, in fact  if we sum for example over Branch we obtain 600, which is clearly wrong (the right total is 150).
Datasets w/o common identifier components are combined with the Cartesian product of the data points, which appears dangerous and semantically inconsistent.
The behaviour on the Data Sets’ Measures of the binary operators (like +, -, *, /, power, nroot … and so on) specified in the reference manual is wrong and not consistent with the “general behaviour of the operators on Data Sets”  specified in the user manual.  In particular, the user manual says that the operation is applied on the Measures of the input Data Sets having the same names and that, to avoid ambiguities and possible errors, the input Data Sets are constrained to have the same Measures, which will be also the measures of the result (if needed the Measure name can be explicitly changed using the Rename clause). Instead the reference manual allows operating Data Set having just one Measure even if the Measure is different, and for this reason creates a new Measure named “Condition” in the Result.
The measure “CONDITION” is often automatically added. The operators behave differently from one another when such a measure is already present. 
The measure created by VTL in automated way is named result instead in the reference manual is called condition. In the line 2685 is also named another variable Value having maybe the same meaning.

**Comment by bellomarini** [comment]
Combination of Datases
------------------------

The correct behavior is the one in the *user manual*, that is, the **strict** one. The *reference manual* should be aligned accordingly.

The combination of two Datasets should be allowed only when the identifier components of one are a subset of the identifier component of the other.

Consider the following example, presenting two decompositions of *deposits*:

DS1: deposits by branch and currency
DS2: deposits by branch and NACE
The relaxed behavior would allow to sum DS1 and DS2:
DS3 = DS1 + DS2 -> deposits by branch, currency and NACE

**DS1**

| **Branch** | **Currency**  | **Value** |
|--|--|--|
| A1 | Euro | 100 |
| A1 | Dollar | 50 |

**DS2**

| **Branch** | **NACE** | **Value** |
|--|--|--|
| A1 | S1 | 70 |
| A1 | S2 | 80 |

**DS3**

| **Branch** | **Currency** | **NACE** | **VALUE** |
| -- | -- | -- | -- |
| A1 | Euro | S1 | 100+70 = 170 |
| A1 | Euro | S2 | 100 + 80 = 180 |
| A1 | Dollar | S1 | 50 + 70 = 120 | 
| A1 | Dollar | S2 | 50 + 80 = 130 |

The result is semantically wrong, since if we sum along **Branch**, we obtain 600, while the total for deposits should be 150. This shows that the relaxed constraint can give rise to inconsistencies.
If we sum over Branch we obtain 600, which not correct.

CONDITION
------------

We should adopt the behavior described in the user manual. The reference manual should be therefore aligned accordingly.

* Many operators take as input Datasets having measures of the same types and produce an output Dataset with the same number of measures with the same types; this is the case of mathematical operators. 
e.g. the Dataset DS1 (ID1, ID2, M1, M2) summed to DS2(ID1, M1, M2) gives rise to DS3(ID1, ID2, M1, M2), where M1 and M2 are numeric.

* Comparison operators take as input Datasets having measures of the same types and produce an output Dataset with the same number of measures, but with boolean types. In facts, the output measures contain the result of the comparison.
e.g. the Datasets DS1(ID1, ID2, M1, M2) compared by ">=" with DS2(ID1, M1, M2) gives rise to DS3(ID1, ID2, M1, M2), where M1 and M2 are boolean, though M1 and M2 in both DS1 and DS2 were numeric.

This being clarified, the safe behavior is:

* Two Datasets can be combined only if they have exactly the same measures (in terms of names and types). The output Dataset thus contains the same measures (in terms of names and types).

* In terms of measures, two Datasets can be combined only if they have measures with the same name and type.
* In the output the measures would have the same name as in the input.
* If the preconditions on names are not satisfied, the RENAME clause (or the rename mechanisms introduced in the core) should be used.
* The behavior would also be the same for mono- and multi-measure case.

e.g. let us suppose we want to compare DS1 (ID1, ID2, MA) + DS2 (ID1, ID2, MB) > DS3 (ID1, ID2, MC).
As the measures have different names, we would write:
DS1[rename MA as M) + DS2[rename MB as M] > DS3[rename MC as M].

**Comment by VincDV** [comment]
As for the **## behavior of the identifier components**, that @bellomarini  calls “**Combination of Datasets**”, I agree with @bellomarini  that the general behavior described in the User Manual is correct and the one described in the Reference Manual is wrong. The default behavior described in the User Manual is also the same as VTL 1.0. In conclusion, the behavior of the operators in the reference manual should be aligned to the general behavior described in the user manual. This is the same conclusion of the Paris meeting, therefore I suggest to consider this first part of the issue as closed.

**Comment by capacma** [comment]
Unfortunately there are still a few open issues concerning the combination of datasets. For example:
- how to manage the combination of a dataset and a scalar, e.g. ds + 0 or ds > 0: the operands do not have the same measures so what is the semantics in this case?
- please see #40 that describes issues related to Boolean expressions and proposes solutions to treat multi-measure datasets
- we should reflect on the constraint the one dataset must have a subset of the dimensions of the other dataset (when combining two datasets). There is no evidence that this limitation is needed.

**Comment by VincDV** [comment]
The secon part of my comment is relevant to the **GENERAL BEHAVIOUR FOR THE MEASURE COMPONENTS**, which correspond to the section "CONDITION" of the @bellomarini comment.  This part is also strictly related with the #40. 

In this context @bellomarini distinguishes  two sub-cases:

1 - Operators for which **the measures of the result are of the same data type (i.e. Value Domains) as the  measures of the operands** (e.g. numeric operators): in this sub-case I agree with the behaviour suggested by @bellomarini, that is the same described in VTL 1.0. 
I also mean that I disagree with the additional behaviour added in VTL 1.1 in respect to VTL 1.0, which is not compliant with the IM, namely:
 > “To avoid a potentially excessive renaming, VTL 1.1 additionally allows operations where each participating dataset has an explicitly specified component using the dot notation. For instance,
> Dr := D1.Residents + D2.Inhabitants 
> creates a result with a single measure component named Result, which can then be renamed, if necessary, at will:
> Dr := (D1.Residents + D2.Inhabitants)[Result->Population]”

In particular, this behaviour is wrong because violates the integrity constraints of the Information Model (the same Variable cannot take values in different Value Domains), in fact the Variable “Result” would take values in the different Value Domains of the operands of different Transformations).  
In conclusion, as well as @bellomarini, I propose to restore the VTL 1.0 behaviour.

2 - Operators for which **the measures of the result are not of the same data type (i.e. Value Domain) as the measures of the operands** (e.g. comparison operators, in which the measures of the result are Boolean independently of the measures of the operands, as well as operators that convert the data type of the operand in another data type for the result). 
In this sub-case, the measures of the result cannot have the same name as the measures of the operands because the value domain of the measures of the result are different from those of the operands (the same Variable cannot take values in different Value Domains). Therefore the @bellomarini proposal should be slightly amended:

a)  Two dataset can be combined only if they have the same measures (same name and type), even following a renaming if needed
b)  The measure variables of the result cannot have the original names as in the operands, because their Value Domains are different; therefore different Variable names are assigned according to the following rules:
- If the result is a mono-measure Data Set, a default Variable having a proper Value Domain is assigned as the measure (the default assignment can be changed through renaming); the possible default Variables correspond to the basic data types/ Value Domains and can be called NumVar, BoolVar, TimeVar, TextVar  respectively for Numeric, Boolean, Date and String data types/Value Domains.  Coherently, VTL assumes that such generic Variables exist by default, even if not explicitly defined. 
- If the result is a multi-measure Data Set, the measure Variables of the result need to be defined explicitly within the expression, in fact the default assignment of the measure variable can generate inconsistencies (the same Variable is not allowed more than once in a Data Structure); to this end, a proper syntax should be defined.

**Comment by VincDV** [comment]
As for the @capacma comments, respectively:

- The semantics of the combination of a dataset and a scalar is explained in the section "Behaviour for Measure Components" of the User Manual (page 90 lines 3016 and following).

- My previous comment can be considered also a comment for the Issue #40 

- The example provided by @bellomarini shows that in case the constraint on the dimensions is removed the result is meaningless and the resulting figures are wrong

**Comment by bellomarini** [comment]
The outcome of the discussion about the first part:

Discussion: automatic vs explicit roll up.

Comparison with explicit join.
The identifiers of one dataset should be contained in the identifiers of another one.

CROSS : no constraints
INNER - OUTER : works on intersection (pivot assumption)
STRICT INNER : additional subset constraint
STRICT OUTER : additional subset constraint

The + would be defined by STRICT INNER and STRICT OUTER.

**Comment by bellomarini** [comment]
The behavior of INNER and OUTER JOINS should be modified in order to allow them to work on datasets with different sets of dimensions.

**Comment by bellomarini** [comment]
Measures
---------

We confirm the general rule that if measures are not compliant with the operator, we obtain an error. 

Unary operators
-----------------
- The membership operator returns a dataset with one measure only that is the chosen one.
- How to select multiple measures to keep in the result and change just one? We have to create some syntax to specify (keep all the others). With the explicit join:

```
[D1] {
measure Import = import * T
}
```

or with calc

```
D1[Import = Import * T]
```

- We change the user manual: 

1. the "." membership keeps only one measure
2. use another syntax, namely join, to alter just one measure and keep all the others in the result.
3. also consider reconciling join and calc (see issue #249 )

Boolean operators
------------------

**Comment by bellomarini** [comment]
see issue #40

**Comment by linardian** [comment]
Notes on obsolete version of documentation
