### ISSUE TITLE
IM for Transformation

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#62]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-2|UM|40|1347
***

### Issue Description
The IM for Transformation is not clear enough, mainly for some kind of operators or complex expressions. There is a paragraph arguing that that some artefacts are hidden for simplicity reasons, but it would be useful to have at least the Expressions artefact in the chart.

### Proposed Solution
Update the Transformations model diagram and give a detailed description how the presented Transformation model operates (i.e. a complete example where a transformation is decomposed into its components in a tree structure and afterwards reengineered from the Transformation model).

**Comment by VincDV** [comment]
In the today teleconference (21/04/2017) it was agreed that it would be preferable not to accept the proposed solution, because the goal of the VTL IM is to describe the Transformations from the perspective of the users which define them more that from the perspective of the IT implementers, instead the users don't need to know the decomposition of a  Transformation in a tree structure (also called abstract syntax tree). Furthermore, there can be many possible approaches to decompose an expression and it would be not opportune to fix as a standard just one approach. On the other side, the introduction of these details would increase the complexity of the IM. This aspect will therefore be considered not as part of the VTL standard but as part of its possible implementations (the implementing institutions may obviously coordinate their solutions).  In any way, the reasons for not representing the syntax trees in the IM should be well explained in the VTL user manual.
As for the Transformation artefact, the parts that compose a Transformation should be better explained, as well as the fact that one ot these part is the Expression, which in the IM is represented in its textual form as an attribute of the Transformation.
