### ISSUE TITLE
Variable scope between different compilation units

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#64]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-GOV-4|UM|47|1622
***

### Issue Description
It is undefined how does "variable scope" feature work between different compilation units. For example module defines Pi number as follows: 
```
module M1, Pi := 3.14, Pi := 3.1415
```
Which is fine, because second variable hides the first one with its scope. However it is undefined which value should be taken when referenced from outside the module. 
```
use module M1, P := M1::Pi * power(R, 2)
```

### Proposed Solution
Discard the implicit variable scope feature of the language. It causes more problems than it solves.  For example: 
```
Pi := 3.14,  Pi := 3.1415
```
should be considered as error.

**Comment by dragan-ivanovic** [comment]
(Note: VTL uses of `;` rather than `,` to separate individual statements.)

While there is generally no confusion about which value of `Pi` remain as the final one in the scope of M1, I acknowledge the point that the programmers may accidentally redefine a variable, which may be a source of errors.

Therefore, we can adopt the proposed solution that assignments to the same name within the same scope are not allowed and are treated as compile time errors.  However, it is allowed to redefine a name in a nested scope, because the names from the nested scope do not propagate upwards, and are therefore invisible when importing from `M1`.

**Comment by linardian** [comment]
Refers to old version of documentation
