### ISSUE TITLE
Component double role "measure & attribute".

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#87]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MTNA-12|UM| |847
***

### Issue Description
It seem conceivable for a component to be both a measure and an attribute. For example "age in years" could be used either as a dimension or measure. How should the variable be defined in that  case?

### Proposed Solution
Provide guidelines or allow for hybrid variables.

**Comment by VincDV** [comment]
In the today teleconference (21/04/2017) it was agreed that the proposed solution cannot be accepted because the VTL Operators may have different behaviours for Identifiers, Measures and Attributes and therefore for each Component a specific role is needed (in case of need, anyway, the RENAME Operator allows to change the role of a Component).
