### ISSUE TITLE
Propagation of Attributes

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/vtl#9]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-8|UM/RM|96|3266
MC-1|UM/RM|97|Attribute propagation
LV-9|UM/RM|98|3335

*** 
### Issue Description
The attribute components paragraph mention the viral characteristic of an attribute but in the DefineDataStructure there is no way to define it.  Also in Join expression we can create attribute but there is no way to specify the virality of an attribute
The approach based on the "viral" property of an attribute is interesting, however the propagation function described in VTL 1.0 is too specific (for example it is not applicable to Eurostat where in general we concatenate the flags in operations, rather than choosing one). 
The default attribute calculation algorithm is not very clear

### Proposed Solution

@capacma
The proposal described below allows performing automatic attribute propagation in a general and precise way. However it should be noted that, as an alternative, we could simply remove the automatic attribute propagation from the RM.
The mechanism is introduced in 3 steps:

1. **Changes to the DDL or DML**
The user specifies when VTL should perform automatic attribute propagation. This can be done as follows (a choice to be made):
a) Specify the **autopropagate** option of the attribute in the definition of the dataset, e.g.
define dataset ds ( 
dimension ref_area ref_area, 
measure obs_value number, 
attribute myAttribute string autopropagate using myFunction
)
b) As an alternative, specify the following declaration in the VTL script that contains the calculations (this option takes into account the comment by Edgardo):
declare myAttribute autopropagate using myFunction
Note that in this case the virality is associated to the attribute name and not to a single dataset. The function myFunction is any function that has the following signature:
define myFunction ( string s1, string s2 ) returns string 
Note: the option can be named **autopropagate** or **viral** as it was in VTL 1.0. This is just a matter of taste.
2. **Change to the DML**
For each expression computed by VTL, if an attribute of the dataset is defined with autopropagate and a value for the specified attribute is not specified in the expression then the value of the attribute is computed automatically using the function specified, combining the attributes in pairs, e.g. if ds has the components described above:
ds1 + ds2 + ds3   
is equivalent to:
{ ds1.obs_value = ds1.obs_value + ds2.obs_value + ds3.obs_value ;
ds2.obs_status := myFunction ( ds1.obs_status, myFunction ( ds2.obs_status , ds3.obs_status )) }
while:
ds1.obs_value + ds2.obs_value + ds3.obs_value
does not fire the automatic attribute propagation because the attribute obs_value is not part of the expression.
For an aggregate operator (that combines many data points into a single data point), the values of the attributes are combined together (in pairs) to compute the value of the attribute for a group of data points  (e.g. sum ( ds ) group by ref_area: one value for IT, one for DE, etc.)
Which are the operators that can fire the automatic propagation:
•	Operators and functions having 2 or more operands
•	aggregate operators (e.g. sum, min, max etc.)
•	time_aggregate
•	aggregate (and the similar operator hierarchy) 
3. **New string functions**
VTL creates several functions on strings that can be used for automatic attribute propagation. These functions should be added to the RM:
define function merge_flags ( string flag1, string flag 2 ) returns string
returns a string built as follows: contatenate flag1 and flag2 to a single string, remove double characters, sort characters in alphabetical order
define function select_flag ( string flag1, string flag 2 ) returns string
returns the flag with the highest weight (of flag1 and flag2 in the value domain)

**Comment by egreising** [comment]
Attributes "calculation" has a different logic than measures calculation. The "virality" is a nice feature but it is too "dangerous" to let it as the default behaviour.
I suggest keeping propagation rules to work by default but only if virality is set "on" explicitly. In other case, the user must include attribute calculation operations.

**Comment by bellomarini** [comment]
I like Maurizio's solution (a) based on a custom function and I'd like to understand it better during the meeting. I have only two concerns about it:

1. does it imply to modify the artifact Dataset in the information model? It appears very clear when we define it in the VTL program, but what happens when it is already defined externally? How to guide the behavior in this case? 
Also, I understand that once defined, the propagation function is implicitly activated. Thus I don't completely understand point 2. of the solution, where we have components specified in the left-hand side of a statement (which so far has not been supported).

2. I would support by default the current behavior, which has been discussed at length during VTL 1.0. At least, there should be a default propagation function with the same behavior as the current one.

**Comment by bellomarini** [comment]
- We agree on the approach.
- More work to be done:

1. update the information model
2. update the definition of the variable artifact in order to add two attributes
3. adding some missing operators included in Maurizio's proposal
4. define a VTL function that uses the propagation method that was present in 1.0
5. the function to calculate attributes is in general a VTL function, which can also be an eval

**Comment by linardian** [comment]
The virality/propagation is a topic currently under revision; in the VTL workshop in Rome (October 2023) it has been decided to pospone tha analysis at a later stage
